version: "3.3"
# Required system defined constants
#
# HOME: Media user's home directory 
# EXT_MOUNT: Directory where external media is mounted
# TZ: Media server's timezome
# PUID: System user ID
# GUID: System group ID
#
# Ports
# Filebrowser: 8010 -> 8080
# Radarr:    : 8050 -> 7878
# Sonarr     : 8060 -> 8989
# Sabnzbd    : 8080 -> 8080
# Plex       : 32400

services:
  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=${TZ}
    ports:
      - 8010:8080
    volumes:
      - ${HOME}/docker/filebrowser/data:/config
      - ${HOME}/downloads:/data/downloads
      - ${EXT_MOUNT}/tv:/data/tv
      - ${EXT_MOUNT}/movies:/data/movies
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/docker/sabnzbd/data:/config
      - ${HOME}/ubuntu/downloads/complete:/downloads
      - ${HOME}/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/docker/sonarr/data:/config
      - ${EXT_MOUNT}/tv
      - ${HOME}/downloads/complete:/downloads
    ports:
      - 8060:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/docker/radarr/data:/config
      - ${EXT_MOUNT}/movies:/movies
      - ${HOME}/downloads/complete:/downloads
    ports:
      - 8050:7878
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional; get from Plex
    volumes:
      - ${HOME}/docker/plex/data/config:/config
      - ${EXT_MOUNT}/tv:/libraries/tv
      - ${EXT_MOUNT}/movies:/libraries/movies
      - /dev/shm/:/config/transcode #OPTIONAL: sets shared memory to the transcode directory
    restart: unless-stopped

# END #
