version: "1.0"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /home/ubuntu/docker/sabnzbd/data:/config
      - /home/ubuntu/downloads/complete:/downloads
      - /home/ubuntu/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /homne/ubuntu/docker/radarr/data:/config
      - /media/ext_media/tv
      - /home/ubuntu/downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /homne/ubuntu/docker/radarr/data:/config
      - /media/ext_media/tv
      - /home/ubuntu/downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
