version: "3.3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=${TZ}
    ports:
      - 8020:8080
    volumes:
      - ${HOME}/docker/config/filebrowser:/config
      - ${HOME}/downloads:/data/downloads
      - ${EXT_MOUNT}/tv:/data/tv
      - ${EXT_MOUNT}/movies:/data/movies
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker/sabnzbd/data:/config
      - /home/ubuntu/downloads/complete:/downloads
      - /home/ubuntu/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker/sonarr/data:/config
      - /ext_media/tv
      - /home/ubuntu/downloads/complete:/downloads
    ports:
      - 8060:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker/radarr/data:/config
      - /ext_media/movies:/movies
      - /home/ubuntu/downloads/complete:/downloads
    ports:
      - 8050:7878
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional; get from Plex
    volumes:
      - /home/ubuntu/docker/plex/data/config:/config
      - /ext_media/tv:/libraries/tv
      - /ext_media//movies:/libraries/movies
      - /dev/shm/:/config/transcode
    restart: unless-stopped
